package model

// Language list: https://cloud.google.com/translate/docs/languages

type LanguageCode string

const (
	Af      LanguageCode = "af"          // Afrikaans
	Sq      LanguageCode = "sq"          // Albanian
	Am      LanguageCode = "am"          // Amharic
	Ar      LanguageCode = "ar"          // Arabic
	Hy      LanguageCode = "hy"          // Armenian
	As      LanguageCode = "as"          // Assamese
	Ay      LanguageCode = "ay"          // Aymara
	Az      LanguageCode = "az"          // Azerbaijani
	Bm      LanguageCode = "bm"          // Bambara
	Eu      LanguageCode = "eu"          // Basque
	Be      LanguageCode = "be"          // Belarusian
	Bn      LanguageCode = "bn"          // Bengali
	Bho     LanguageCode = "bho"         // Bhojpuri
	Bs      LanguageCode = "bs"          // Bosnian
	Bg      LanguageCode = "bg"          // Bulgarian
	Ca      LanguageCode = "ca"          // Catalan
	Ceb     LanguageCode = "ceb"         // Cebuano
	ZhCN    LanguageCode = "zh-CN"       // Chinese Simplified
	ZhTW    LanguageCode = "zh-TW"       // Chinese Traditional
	Co      LanguageCode = "co"          // Corsican
	Hr      LanguageCode = "hr"          // Croatian
	Cs      LanguageCode = "cs"          // Czech
	Da      LanguageCode = "da"          // Danish
	Dv      LanguageCode = "dv"          // Dhivehi
	Doi     LanguageCode = "doi"         // Dogri
	Nl      LanguageCode = "nl"          // Dutch
	En      LanguageCode = "en"          // English
	Eo      LanguageCode = "eo"          // Esperanto
	Et      LanguageCode = "et"          // Estonian
	Ee      LanguageCode = "ee"          // Ewe
	Fil     LanguageCode = "fil"         // Filipino (Tagalog)
	Fi      LanguageCode = "fi"          // Finnish
	Fr      LanguageCode = "fr"          // French
	Fy      LanguageCode = "fy"          // Frisian
	Gl      LanguageCode = "gl"          // Galician
	Ka      LanguageCode = "ka"          // Georgian
	De      LanguageCode = "de"          // German
	El      LanguageCode = "el"          // Greek
	Gn      LanguageCode = "gn"          // Guarani
	Gu      LanguageCode = "gu"          // Gujarati
	Ht      LanguageCode = "ht"          // Haitian Creole
	Ha      LanguageCode = "ha"          // Hausa
	Haw     LanguageCode = "haw"         // Hawaiian
	He      LanguageCode = "he"          // Hebrew
	Hi      LanguageCode = "hi"          // Hindi
	Hmn     LanguageCode = "hmn"         // Hmong
	Hu      LanguageCode = "hu"          // Hungarian
	Is      LanguageCode = "is"          // Icelandic
	Ig      LanguageCode = "ig"          // Igbo
	Ilo     LanguageCode = "ilo"         // Ilocano
	Id      LanguageCode = "id"          // Indonesian
	Ga      LanguageCode = "ga"          // Irish
	It      LanguageCode = "it"          // Italian
	Ja      LanguageCode = "ja"          // Japanese
	Jv      LanguageCode = "jv or jw"    // Javanese
	Kn      LanguageCode = "kn"          // Kannada
	Kk      LanguageCode = "kk"          // Kazakh
	Km      LanguageCode = "km"          // Khmer
	Rw      LanguageCode = "rw"          // Kinyarwanda
	Gom     LanguageCode = "gom"         // Konkani
	Ko      LanguageCode = "ko"          // Korean
	Kri     LanguageCode = "kri"         // Krio
	Ku      LanguageCode = "ku"          // Kurdish
	Ckb     LanguageCode = "ckb Kurdish" // Kurdish (Sorani)
	Ky      LanguageCode = "ky"          // Kyrgyz
	Lo      LanguageCode = "lo"          // Lao
	La      LanguageCode = "la"          // Latin
	Lv      LanguageCode = "lv"          // Latvian
	Ln      LanguageCode = "ln"          // Lingala
	Lt      LanguageCode = "lt"          // Lithuanian
	Lg      LanguageCode = "lg"          // Luganda
	Lb      LanguageCode = "lb"          // Luxembourgish
	Mk      LanguageCode = "mk"          // Macedonian
	Mai     LanguageCode = "mai"         // Maithili
	Mg      LanguageCode = "mg"          // Malagasy
	Ms      LanguageCode = "ms"          // Malay
	Ml      LanguageCode = "ml"          // Malayalam
	Mt      LanguageCode = "mt"          // Maltese
	Mi      LanguageCode = "mi"          // Maori
	Mr      LanguageCode = "mr"          // Marathi
	MniMtei LanguageCode = "mni-Mtei"    // Meiteilon (Manipuri)
	Lus     LanguageCode = "lus"         // Mizo
	Mn      LanguageCode = "mn"          // Mongolian
	My      LanguageCode = "my Myanmar"  // Myanmar (Burmese)
	Ne      LanguageCode = "ne"          // Nepali
	No      LanguageCode = "no"          // Norwegian
	Ny      LanguageCode = "ny Nyanja"   // Nyanja (Chichewa)
	Or      LanguageCode = "or Odia"     // Odia (Oriya)
	Om      LanguageCode = "om"          // Oromo
	Ps      LanguageCode = "ps"          // Pashto
	Fa      LanguageCode = "fa"          // Persian
	Pl      LanguageCode = "pl"          // Polish
	Pt      LanguageCode = "pt"          // Portuguese (Portugal, Brazil)
	Pa      LanguageCode = "pa"          // Punjabi
	Qu      LanguageCode = "qu"          // Quechua
	Ro      LanguageCode = "ro"          // Romanian
	Ru      LanguageCode = "ru"          // Russian
	Sm      LanguageCode = "sm"          // Samoan
	Sa      LanguageCode = "sa"          // Sanskrit
	Gd      LanguageCode = "gd"          // Scots Gaelic
	Nso     LanguageCode = "nso"         // Sepedi
	Sr      LanguageCode = "sr"          // Serbian
	St      LanguageCode = "st"          // Sesotho
	Sn      LanguageCode = "sn"          // Shona
	Sd      LanguageCode = "sd"          // Sindhi
	Si      LanguageCode = "si"          // Sinhala (Sinhalese)
	Sk      LanguageCode = "sk"          // Slovak
	Sl      LanguageCode = "sl"          // Slovenian
	So      LanguageCode = "so"          // Somali
	Es      LanguageCode = "es"          // Spanish
	Su      LanguageCode = "su"          // Sundanese
	Sw      LanguageCode = "sw"          // Swahili
	Sv      LanguageCode = "sv"          // Swedish
	Tl      LanguageCode = "tl"          // Tagalog (Filipino)
	Tg      LanguageCode = "tg"          // Tajik
	Ta      LanguageCode = "ta"          // Tamil
	Tt      LanguageCode = "tt"          // Tatar
	Te      LanguageCode = "te"          // Telugu
	Th      LanguageCode = "th"          // Thai
	Ti      LanguageCode = "ti"          // Tigrinya
	Ts      LanguageCode = "ts"          // Tsonga
	Tr      LanguageCode = "tr"          // Turkish
	Tk      LanguageCode = "tk"          // Turkmen
	Ak      LanguageCode = "ak"          // Twi (Akan)
	Uk      LanguageCode = "uk"          // Ukrainian
	Ur      LanguageCode = "ur"          // Urdu
	Ug      LanguageCode = "ug"          // Uyghur
	Uz      LanguageCode = "uz"          // Uzbek
	Vi      LanguageCode = "vi"          // Vietnamese
	Cy      LanguageCode = "cy"          // Welsh
	Xh      LanguageCode = "xh"          // Xhosa
	Yi      LanguageCode = "yi"          // Yiddish
	Yo      LanguageCode = "yo"          // Yoruba
	Zu      LanguageCode = "zu"          // Zulu
)
